name: Deploy Application

on:
  push:
    branches:
      - devops/container

jobs:
  deploy:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        # switches: -avzr --delete --exclude=".git" --exclude=".github" --include="" --filter=""
        path: laravel-todolist-api
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
