name: Deploy Laravel Application

on:
  push:
    branches:
      - devops/container
    
jobs:
  deploy:
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Workspace Contents
        run: |
          echo "Workspace Directory: ${{ github.workspace }}"
          ls -la 
          pwd

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: "${{ github.workspace }}/"
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Debug Workspace Contents
        run: |
          echo "Workspace Directory: ${{ github.workspace }}"
          ls -la 
          pwd

      - name: Run Laravel Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            composer install --optimize-autoloader --no-dev
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
